### ISSUE TITLE
Original PWings have fat left wing syndrome

### ISSUE THREAD

**Issue by Crzyrndm** [ferram4/Ferram-Aerospace-Research#123]
http://imgur.com/gswE9kq

Happens on release and latest github build, with or without the "use meshes" override (verified MM cache that changes applied)
```
@MODULE[GeometryPartModule]
{
	%forceUseMeshes = True
}
```

* B9 PWings are not affected (using the mesh override)
* Mirroring axis is (0,0,-1)

**Comment by ferram4** [comment]
Well, then this is a problem that needs to be fixed on the original Pwings side.  Every other part in the game, when making use of mirroring that will flip the handedness of the triangles on the wings sets Part.isMirrored to true or in some way makes proper use of the mirror axis mechanics in game.  B9 Pwings does this as well.

I have no means to detect when triangles are not oriented the correct way.  All my attempts to do so when trying to not rely on KSP's system for B9 Pwings have failed, so this means all fixes need to happen on that end.

Since this isn't a FAR issue at its root, but a Pwings issue, I'll be closing this.
