### ISSUE TITLE
Files for configuration that are written to disk on every session should be stored in the "PluginData" folder.

### ISSUE THREAD

**Issue by Galenmacil** [ferram4/Ferram-Aerospace-Research#143]
This is to avoid module manager rebuilding the patches on each game loading instead of using the much faster cache. Read this for more information: https://github.com/m4v/RCSBuildAid/issues/32.

**Comment by blowfishpro** [comment]
Is there a specific file that ModuleManager claimed was changed in FAR?  My understanding was that FAR has done this correctly since forever.

**Comment by ferram4** [comment]
There is exactly one file that will change every time the game loads: FerramAerospaceResearch/Plugins/PluginData/config.xml.  Note that it is already within PluginData.

All other files that can change (the CustomFAR*.cfg files) 1) cannot be placed inside of PluginData because they act through MM, and so must trigger a MM rebuild when they change, and 2) in standard usage do not change between sessions unless modified using the in-game settings, by another mod or by a mod manager.

Therefore, this feature is already implemented to the fullest extent that it can be.
