### ISSUE TITLE
1.2.2 SPH Problems

### ISSUE THREAD

**Issue by Maeyanie** [ferram4/Ferram-Aerospace-Research#157]
Using FAR ea259a, KSP 1.2.2, and MFI 1.2.3, on a heavily-modded install.

I put together some plane bits, clicked the "Show CoL" button, it flickered for a moment then vanished. FAR's UI didn't work either. Checking the log, there seems to be a number of different errors. It's attached.

This seems to be a mod-interaction issue, as I wasn't able to reproduce it with a minimal set. I'll see if I can narrow down exactly what caused it and update this thread.

[output_log.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/662532/output_log.zip)

**Comment by Maeyanie** [comment]
Found it.
Steps to reproduce: Add an F-5 cockpit from the [MTA Stockalike](http://forum.kerbalspaceprogram.com/index.php?/topic/118388-master-tech-aerospace/) mod. FAR fails to voxelize it, and everything breaks.

**Comment by ferram4** [comment]
I'm investigating, and there appears to be at least one bug in this that I've already fixed.  However, I'm not exactly sure what the cause of everything going NaN is and while I might be able to fix it, usually that points to issues with the mesh itself in some way.

**Comment by Maeyanie** [comment]
I went to test this again with the updated ea259af5989ee0826b18c346cc748741672c81f5 version, and it doesn't seem to load properly:
```
AssemblyLoader: Exception loading 'FerramAerospaceResearch': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 
```
Full log attached.
[output_log.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/664682/output_log.zip)

**Comment by Maeyanie** [comment]
In case you get these by e-mail, disregard last (now deleted) message, I'm just a derp and downloaded the wrong branch.

**Comment by Maeyanie** [comment]
Still seems to happen in ea8f428c07e8da68aaecbd54176779bee6eb8214.
Though I did notice loading a craft which contains the broken part seems to work fine, it's just creating a vessel by adding a new one which breaks.

**Comment by NathanKell** [comment]
self-poking so I remember

**Comment by ferram4** [comment]
Found it!  So the problem did come down to the embedded intake module, in a roundabout way.  It's also related to the main axis determination system as well.

So in order to determine the main axis I use a lot of hints about vehicle shape, one of those being intake orientation, since those should be (largely) facing forward.  But I can't just use the intake *part* orientation, because that's all over the place compared to the directional intake transform on the mesh.  So I use the intake transform from the mesh.

But sometimes that's borked for a mod part due to insufficient testing, so I fall through instead and provide no contribution to the main axis from that part if that happens.  But if that's the only part, there is no main axis data.  It tries to work with a (0,0,0) vector for that and it breaks.

So I added a failsafe for that and now it works, thanks for the report!
