### ISSUE TITLE
Wing clipping possibly results in strange behavior

### ISSUE THREAD

**Issue by Qromodynmc** [ferram4/Ferram-Aerospace-Research#161]
Hello Ferram, 
I was having some kind of unusual behavior on my planes and tried to find out what was causing to it and eventually settled on these wing connector parts, here is the issue;
 These parts makes control surfaces ineffective; but i also believe control surfaces dont work because wings have no lift. 
Planes that have these parts stall lot higher speeds than planes who doesnt use them. Again makes me think these parts dont have correct lift features.
![far issue](https://cloud.githubusercontent.com/assets/24719758/21432046/d19ca1f6-c87a-11e6-9a79-894d538cc778.png)
I made this plane just to see full effect of issue, it's totally unflyable. 
------------
Im using x64 ksp, with some mods but they are purely part mods.
also confirmed issue by some friends.
I have latest version of Module manager and MFI.
And at last, this issue was there in 1.1 too.
Hope you can enlighten me, and good luck.

**Comment by ferram4** [comment]
I have built a plane identical in shape to what you have shown.  Of the 3 fuselage parts behind the cockpit, only the middle one is a fuel tank.  Control surfaces are limited to only pitch, yaw, and roll.

The only problems I can find with it are that it is slightly too statically stable and is somewhat lacking in yaw stability, particularly at high angles of attack.  Otherwise, it flies perfectly fine.  I see some minor differences in flight behavior between different parts, but I see no issues specific to these parts.

Either you have another mod that is interfering with the FAR dev build or you are missing crucial reproduction steps.

**Comment by Qromodynmc** [comment]
Today i tried Vanilla 1.2.2, with dev build, module manager 2.7.5 and mfi, still same issue, i recorded a video about it;
https://youtu.be/vEO-JJmAd0Y
if there is something you want me to do extra, do tell.

**Comment by ferram4** [comment]
That looks very much like a case of a plane that is too stable for the amount of control authority it has, not so much like an aerodynamic bug, tbh.  It especially behaves exactly as I would expect for a vehicle with a large amount of pitch stability when it is brought supersonic, where it would be *even more* stable.

But in any case, assuming that there are any errors, those would be caused by the copious amount of wing part clipping.  Until a complete wing code overhaul can be done, any issues involving that cannot be addressed and will not be addressed for the next update.

**Comment by Vladokapuh** [comment]
Hey, I built three test planes, as im pretty sure theres something odd with D wing connector.
All three planes have mostly the same shape, but they interchange E connectors for D.
Plane using E connectors flies just fine. 
![e](https://cloud.githubusercontent.com/assets/24779063/21484279/50dab116-cb90-11e6-8f31-50b0c78fca9d.jpg)
Plane using one D connector where ailerons are flies, but will not roll unless speeds get very high.
![d](https://cloud.githubusercontent.com/assets/24779063/21484276/46e2c770-cb90-11e6-9b53-6c72cf6fcfe5.jpg)
Plane using D connectors both at elevator and aileron, wont even lift off.
![d2](https://cloud.githubusercontent.com/assets/24779063/21484246/ba611202-cb8f-11e6-9829-a9c101980881.jpg)

D wing connector seems to somehow almost entirely block control surfaces attached to it, and they only start working (poorly) at high speeds. (above around mach 0.8)

[!!!!!!!!!!!!!!]
For some reason i couldnt upload a zip, so i renamed it to docx, just change name back to .zip and it should open if you want to investigate on this
[bugtest planes.docx](https://github.com/ferram4/Ferram-Aerospace-Research/files/673163/bugtest.planes.docx)

**Comment by ferram4** [comment]
Welp, I found it.  Error introduced awhile back when maintaining legacy stuff.  Fixed.
