### ISSUE TITLE
Low drag

### ISSUE THREAD

**Issue by Maeyanie** [ferram4/Ferram-Aerospace-Research#207]
A few people have recently mentioned drag being implausibly low, and I'd noticed similar... there were always explanations of "too used to stock aero" and "stock jets are too powerful" and such, which seemed legitimate. But recently I put together a plane which I'm pretty sure isn't right.

I used an AJE Su-27 x2 engine, which gave thrust significantly lower than an actual Su-27; KSP showed me having 48.8 kN total in cruise, Wikipedia says the real ones are a much higher 75.22 kN each. The takeoff weight was fairly similar (30,790 kg vs. 30,450 kg). I'm sure Sukhoi also did a much better job at aerodynamic optimizing than me, so I would've expected to have worse performance.

Despite this, I was able to supercruise at around mach 1.6 on the way out, fired some SRBs to do a high-atmo hop (didn't quite make the suborbital the contract wanted) then with the lighter weight supercruised at mach 2 on the way back.

[Screenshot on the way out](https://www.dropbox.com/s/dxuhrtv1jdc0r20/Kerbal%20Space%20Program%202017.06.23%20-%2023.21.21.61.png)

[Screenshot on the way back](https://www.dropbox.com/s/i348o5f57017fzv/Kerbal%20Space%20Program%202017.06.24%20-%2001.25.08.67.png)

[Craft file](https://www.dropbox.com/s/40yeg8yhhdul4s4/Phoenix.craft)

"But Maey," you ask. "There's a pile of mods in those screenshots, maybe one of them is doing it?" That occurred to me too, but I was able to build a similar craft with stock parts and a minimal mod set, and got around [mach 1.36 cruise speed](https://www.dropbox.com/s/6v2ubr60fc5k5d5/Kerbal%20Space%20Program%202017.06.27%20-%2023.26.21.99.png).
It isn't shaped as nicely, and the engines give less thrust, but it's also much lighter (20,347 kg). I'm still pretty sure it shouldn't be that good.
[Craft file](https://www.dropbox.com/s/vwdhs0m0rc2as2a/Test.craft)
[Log file](https://www.dropbox.com/s/uoddra4z7ln74yr/KSP.log)

**Comment by ferram4** [comment]
1) You're comparing static thrust to in-flight thrust.  They're very different, don't compare those things.
2) FAR is, by default, very forgiving about aerodynamic shaping compared to reality.  This is because of the lack of shaping we can do and the fact that the voxel resolution sets an upper limit on how accurate things can be.  The combo is that your design is almost certainly considered by FAR to be far, far more aerodynamic than an Su-27.

Change the FAR settings in the space center to "Full Drag, Strict Area Ruling" which is as close to reality as is possible, but is virtually impossible to do anything with in the stock game.

All of that said, I don't believe that there is an actual issue here, so I'm closing this.

**Comment by Maeyanie** [comment]
Well, AJE's thrust isn't your problem; I'm just mentioning it since it's not unrealistically high.

Mostly, the problem is that even with the (presumably) near-ideal area ruling done by a professional aircraft manufacturer, a craft of that weight and engine isn't capable of speeds even close to what I'm seeing without using its afterburners.

Now, it's not entirely a bad thing, as it helps KSP planes be less boring, and we can use large airbrakes and spoilers for slowing down enough to land. I'm just not sure this is realistic, even accounting for the default "full drag, moderate area ruling" setting.

**Comment by Maeyanie** [comment]
Okay... I switched the setting to "full drag, strict area ruling" as you suggested, and did another flight with the same test plane as above.
It supercruised at [mach 1.31](https://www.dropbox.com/s/dtt3ex0exm8itfq/Kerbal%20Space%20Program%202017.06.28%20-%2001.34.57.103.png).

**Comment by ferram4** [comment]
"Full Drag" is referring to an overall scalar for wave drag based on area ruling.  The strict setting changes it from FAR smoothing the overall shape more to smoothing it less, effectively modelling more what is actually there rather than a more ideal approximation.  And based on your testing, it sounds right for a very clean configuration using those engines.

**Comment by Maeyanie** [comment]
Hm, well, you know a lot more about this stuff than I do, so if you say it's legit, I'll believe you. Thanks for looking into this.
