### ISSUE TITLE
Error in Stab Deriv Xu Calc

### ISSUE THREAD

**Issue by oscardssmith** [ferram4/Ferram-Aerospace-Research#223]
I've made a plane with Xu=.198. Apparently this shouldn't happen. How should I attach data to allow for debugging?

**Comment by ferram4** [comment]
The craft file, a full list of the mods *absolutely required* for the craft, and that should be it.  Before you do that though, check to make sure that the sim is actually converging; make sure that the steady AoA for that situation is relatively low (not 0 exactly), because otherwise indicates a failure to calculate steady flight at all.

**Comment by oscardssmith** [comment]
Steady state AoA is reported as ">0 deg" Does that mean the simulation failed?

**Comment by ferram4** [comment]
Yep, it failed to converge because the craft is too heavy for that speed.  It should be fine if you increase the speed to something more reasonable for its mass.  I'll close this then, since unless the behavior persists at a low AoA then there is nothing wrong.

**Comment by oscardssmith** [comment]
Could steady state AoA be color coded red if it fails to converge, or could there be some other way to indicate that the velocity is too low for steady state flight?
