### ISSUE TITLE
Terminal velocities / Ballistic Coefficient (and maybe others?) data in Editor

### ISSUE THREAD

**Issue by fommil** [ferram4/Ferram-Aerospace-Research#46]
I love this mod so much!

I would like to be able to chart out the terminal velocities for a spacecraft on various planets, at various heights. I assume that, in FAR, this depends on the rocket (unlike stock, which looks like it is a simple lookup table).

Is there any possibility of you providing a calculator to do this, or (possibly more fun!) a science experiment to measure it.

**Comment by erendrake** [comment]
From my conversations with ferram, Terminal velocity is not as important as it is in stock aero. as far as i know there is no single number you can use to determine the success of a mission. 

MaxQ is pretty important

**Comment by ferram4** [comment]
FAR's Flight Data already has an estimated terminal velocity readout.  Actually providing a calculator out of game to solve this is pretty much not going to happen, since there are so many variables and I can't get them all out-of-game.  Most importantly, geometry (for each part on the rocket), angle of attack, Mach number, mass, etc.

In game, it's already there though.

**Comment by fommil** [comment]
Cool, I never knew about it. Can I get it to generate / persist a graph? Altitude vs value, for example.

**Comment by ferram4** [comment]
No, it's not set up to do that.  It should be possible with some other plugin, perhaps using kOS or RPM to read the values through FAR's API, but I don't know.

**Comment by fommil** [comment]
btw, I'm not looking for a calculator out of game: I mean for during vehicle construction. There is loads for spaceplanes (AoA, etc), but not much for rockets.

**Comment by ferram4** [comment]
For rockets, it's largely not worth it for terminal velocity readouts simply because there are so many variables based on how much fuel, what orientation, current altitude, etc.  Although, as a result of the magnitude of the forces involved here, worrying about terminal velocity for a rocket is kind of crazy.

I'll look into adding a ballistic coefficient readout somewhere in the editor though (it's like a gravity-and-density-independent means of measuring terminal velocity).  Heating though, I don't know if I can do that.  I know that the current DRE model assumes that shock temperature in Kelvin ~= velocity in m/s, which isn't bad for Earth reentry velocities (7.5 km/s - 12 km/s), but overestimates at lower velocities and underestimates somewhat at higher velocities.

**Comment by fommil** [comment]
Excellent, thanks! Anything that helps make better rockets and reentry pods is great
