### ISSUE TITLE
Toggling landing gear causes aircraft to nosedive

### ISSUE THREAD

**Issue by mjn33** [ferram4/Ferram-Aerospace-Research#58]
**Operating System:** Fedora 21 (Linux) x86-64

Using FAR from the voxelAeroPort branch, commit b9e604fe0ce650173bd332d08b756a47499c979b.
Using a fresh install with no other mods.

**Reproduction steps:**
 1. Go to the SPH
 2. Load "FAR Colibri" from FAR v0.14.7
 3. Launch & takeoff (I only used the rear engine)
 4. Toggle landing gear

**Expected result:**
The landing gear retract and the aircraft flies normally. 

**Actual result:**
The Cl value in the FAR Flight Data GUI will drop to a large negative value and the plane nosedives, it tends to sort itself out given time (although not always). This also happens if I open and close the cargo bay doors, and on the odd occasion causes rapid unplanned disassembly. 

[screenshot0.png](https://dl.dropboxusercontent.com/u/15422248/screenshot0.png) (shortly after takeoff)
[screenshot1.png](https://dl.dropboxusercontent.com/u/15422248/screenshot1.png) (retracting landing gear causing nosedive)
[screenshot3.png](https://dl.dropboxusercontent.com/u/15422248/screenshot3.png) (recovered from nose dive)
[screenshot4.png](https://dl.dropboxusercontent.com/u/15422248/screenshot4.png) (happens again when deploying)
[screenshot10.png](https://dl.dropboxusercontent.com/u/15422248/screenshot10.png) (doomed)

Contents of Player.log here: https://dl.dropboxusercontent.com/u/15422248/Player.log

**Comment by ferram4** [comment]
Alright, thank you for this.  Turns out that it was a race condition between the voxelization and aero properties thread and the main thread.

So the voxelization and aero properties determination methods run in another thread (the voxel itself takes a few of its own as well) so that it can work without slowing down the game.  Now, at the end of it, it applies these properties to each of the parts, dividing them up as necessary so that each gets its own correct properties.  This requires knowledge of the part's orientation and position in space.

So the aero properties are first calculated in the vessel-local frame, with the transform matrix to world-space calculated right at the start.  At the end, the properties are converted to world-space, then to part-local-space to apply them to the parts.  However, I was calculating the part-local transform matrix at the end, which was almost certainly not the same frame as the vessel matrix.  For some of them, it wasn't even the same frame between parts, hence the disintegration.

So switching to calculating all the part transforms at the beginning and passing them through fixes this.  That version of the Colibri is, unfortunately, unstable in virtually all conditions now, but at least it's consistent.
